### ISSUE TITLE
Why is the element itself stored in "dom"?

### ISSUE THREAD

**Issue by kurtextrem** [bendc/sprint#14]
That breaks compatibility with jQuery. Example:
`$('body')[0].id` 
Works in jQuery.

While Sprint would be:
`$('body').dom[0].id`

**Comment by bendc** [comment]
You should use `.get()` instead of the `dom` property. Sprint doesn't generate array-like objects like jQuery, it just creates raw JS objects each time $ is called.

**Comment by kurtextrem** [comment]
Thanks. Maybe that should be pointed out somewhere.
