### ISSUE TITLE
How to implement with jQuery?

### ISSUE THREAD

**Issue by GlassGruber** [bendc/sprint#17]
Maybe I'm asking a dumb question, I see that this is an "alternative" not a replacement, but I can't find any proper info on how to deal with jQuery and Sprint together on the same page.
So basically, how can I use Sprint along with jQuery? 
I have some plugins with jQuery dependancy, how should I proceed to implement Sprint?
Since the same API is used will there be conflicts if both scripts are present?

**Comment by visualcookie** [comment]
Sprint is a jQuery replacement, from what I understand. So you can't use Sprint and jQuery at the same time.

**Comment by kurtextrem** [comment]
Well, you could. Sprint only sets $, if it hasn't been set yet. Doesn't change the fact that it would make no sense though.

**Comment by Charca** [comment]
You can test if your jQuery plugins work with Sprint instead, and then replace it.

**Comment by stephnr** [comment]
I dont see why you cant use them both.

If using jQuery, use the `jQuery` variable for jQuery statements. Since Sprint uses the $ operator, you cannot use it for jQuery.

**Comment by visualcookie** [comment]
@Stephn-R Well but jQuery uses `$` as well as `jQuery` and most plugins are written with the dollar.

**Comment by manuganji** [comment]
Even I had the same question. If its not a full replacement, there should be a way to use the good parts of sprint where possible and fallback to jquery where its not possible.

**Comment by jquense** [comment]
just reassign the $ to a global Sprint variable and they you can have jquery use the $

**Comment by GlassGruber** [comment]
A full replacement could be a good suggestion, still it requires quite some trial and testing for the stability, and probably some edge cases could slip. I guess that a reassigning the $ for Sprint is a good way too, but wouldn't this fail in the main purpose of the library to reuse already built jQuery code?

**Comment by jquense** [comment]
I'm pretty sure the main purpose of the library to offer a jquery alternative for modern browsers, not to reuse or augment jquery. "Alternative"  here doesn't mean use them together,  it means "not trying to solve all the same things as jquery although there is overlap". e.g. Dom API sugar but no xhr wrapper.

**Comment by stephnr** [comment]
I hate to be the guy to ask the question but why dont we choose a different selector?

**Comment by bendc** [comment]
You can actually use jQuery and Sprint at the same time: Sprint always exposes the `Sprint` global variable and uses `$` as an alias only if it's available. So, if you wanna use both on the same document, you can mix `$()` and `Sprint()` calls :

``` javascript
$("body").addClass("foo"); // uses jQuery
Sprint("body").addClass("bar"); // uses Sprint
```

**Comment by GlassGruber** [comment]
That's quite nice and simple! I suggest to put this into a simple note in the docs or FAQ. Thank you!
