### ISSUE TITLE
No selector support for .on/.off?

### ISSUE THREAD

**Issue by brandonros** [bendc/sprint#19]
For dynamically loaded/drawn content, it's required to write code like:

```
$(document).off('event', 'selector').on('event', 'selector', function (event) { 
 ... 
})
```

no?

How else could Sprint currently be used?

**Comment by bendc** [comment]
You can do something like this:

``` javascript
$(document).on("click", function(e) {
  if ($(e.target).is(selector)) // do something
});
```

**Comment by brandonros** [comment]
I do not think this would work for real world practices, with scripts being dynamically loaded and selectors being reused. 

Also, this would lead to one giant on click function?
